"""Authoring generator for NEW candidate exchange contracts; never imports existing schemas."""
import copy,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
def write(p,v):
 (R/p).parent.mkdir(parents=True,exist_ok=True);(R/p).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def digest(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def obj(props,required=None):return {'type':'object','properties':props,'required':list(props) if required is None else required,'additionalProperties':False}
def arr(s,minimum=0):return {'type':'array','items':s,'minItems':minimum}
def enum(*s):return {'type':'string','enum':list(s)}
S={'type':'string','minLength':1}; B={'type':'boolean'}; ID={'type':'string','pattern':'^SIM[-.]'}; H={'type':'string','pattern':'^[0-9a-f]{64}$'}; VER={'type':'string','pattern':r'^\d+\.\d+\.\d+$'}; MONEY={'type':'string','pattern':r'^-?\d+\.\d{2}$'}; DATE={'type':'string','pattern':r'^\d{4}-\d{2}-\d{2}$'}
REF=obj({'id':S,'version':VER});SCOPE=obj({'tenantId':S,'orgIds':arr(S,1),'customerIds':arr(S),'purpose':enum('RESEARCH','INTERPRETATION','RECOMMENDATION')});PERIOD=obj({'from':DATE,'to':DATE});LOC=obj({'sourceId':S,'sourceVersion':VER,'path':S,'quote':S,'quoteHash':H,'sourceHash':H})
scope={'tenantId':'SIM-BANK','orgIds':['SIM-O01'],'customerIds':['SIM-C001'],'purpose':'INTERPRETATION'}
base={'contractVersion':{'const':'gk-ke/v1'},'simulationOnly':{'const':True}}; schemas={};examples={}
def add(name,props,val,required=None):
 schema={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':f'https://contracts.example.invalid/gk-ke/v1/{name}.schema.json','title':name,'description':'独立候选交换剖面；SIM-only 示例约束，非现有生产合同替代。',**obj({**base,**props},None if required is None else ['contractVersion','simulationOnly']+required)}
 schemas[name]=schema;examples[name]={'contractVersion':'gk-ke/v1','simulationOnly':True,**val}
add('SemanticPackage',{'packageId':S,'version':VER,'ownerSystem':enum('CORE'),'types':arr(obj({'typeId':S,'definition':S,'identityRule':S}),1),'imports':arr(REF)}, {'packageId':'SIM-CORE','version':'1.0.0','ownerSystem':'CORE','types':[{'typeId':'core.Customer','definition':'银行业务服务对象，实例身份由源客户主档维护','identityRule':'customerId稳定且不可由名称替代'},{'typeId':'core.Money','definition':'具有币种和单位的金额值','identityRule':'decimal+currency+unit'}],'imports':[]})
asset={'assetId':'SIM-ASSET-P001','version':'1.0.0','assetClass':'KNOWLEDGE_RULE','kind':'PRODUCT_CARD','title':'模拟流动资金贷条款','ownerSystem':'KERT','ownerRole':'SIM-KNOWLEDGE-OWNER','contentRef':'simulation/documents/SIM-DOC-P001_1.0.0.md','contentHash':hashlib.sha256((R/'simulation/documents/SIM-DOC-P001_1.0.0.md').read_bytes()).hexdigest(),'coreVersion':'1.0.0','scope':scope,'purposeFlags':['INTERPRETATION'],'lifecycle':'PUBLISHED','dependencyRefs':[]}
add('AssetVersion',{'assetId':S,'version':VER,'assetClass':enum('FOUNDATIONAL_DATA','KNOWLEDGE_RULE','PROCESS_TOOL','RUNTIME_FEEDBACK'),'kind':enum('PRODUCT_CARD','DOCUMENT','RULE','METRIC','QUERY','SKILL','DATA_SERVICE','MAP','FEEDBACK'),'title':S,'ownerSystem':enum('CORE','BANK_SOURCE','SEMANTIC_SERVICE','KERT','GITS'),'ownerRole':S,'contentRef':S,'contentHash':H,'coreVersion':VER,'scope':SCOPE,'purposeFlags':arr(enum('RESEARCH','INTERPRETATION','RECOMMENDATION'),1),'lifecycle':enum('CANDIDATE','IN_REVIEW','APPROVED','PUBLISHED','REVOKED'),'dependencyRefs':arr(REF)},asset)
mapvalue={'mapId':'SIM-MAP-FINANCE','version':'1.0.0','releaseId':'SIM-REL-001','taskTypes':['FINANCE_VISIT_PREP'],'entryNodes':['N-TASK'],'routePolicyRef':{'id':'SIM-ROUTE-001','version':'1.0.0'},'nodes':[{'nodeId':'N-TASK','nodeType':'Task','label':'访前融资讨论','ref':{'id':'SIM-TASK-TEMPLATE','version':'1.0.0'}},{'nodeId':'N-PRODUCT','nodeType':'Asset','label':'产品说明','ref':{'id':'SIM-ASSET-P001','version':'1.0.0'}},{'nodeId':'N-METRIC','nodeType':'Asset','label':'日均存款','ref':{'id':'SIM-ASSET-METRIC','version':'1.0.0'}},{'nodeId':'N-SKILL','nodeType':'Capability','label':'产品解读','ref':{'id':'SIM-CAP-INTERPRET','version':'1.0.0'}}],'edges':[{'edgeId':'SIM-ME-1','from':'N-TASK','to':'N-PRODUCT','relation':'requires','reason':'解读产品须引用受控条款','designDecisionRef':'SIM-MAP-DESIGN-001'},{'edgeId':'SIM-ME-2','from':'N-TASK','to':'N-METRIC','relation':'requires','reason':'访前核对客户余额口径','designDecisionRef':'SIM-MAP-DESIGN-001'},{'edgeId':'SIM-ME-3','from':'N-TASK','to':'N-SKILL','relation':'requires','reason':'按稳定知识入口交付产品解释','designDecisionRef':'SIM-MAP-DESIGN-001'},{'edgeId':'SIM-ME-4','from':'N-SKILL','to':'N-PRODUCT','relation':'uses','reason':'能力依赖产品条款','designDecisionRef':'SIM-MAP-DESIGN-001'}],'purpose':'INTERPRETATION','scope':scope}
add('KnowledgeMap',{'mapId':S,'version':VER,'releaseId':S,'taskTypes':arr(S,1),'entryNodes':arr(S,1),'routePolicyRef':REF,'nodes':arr(obj({'nodeId':S,'nodeType':enum('Task','KnowledgeDomain','Asset','Capability'),'label':S,'ref':REF}),1),'edges':arr(obj({'edgeId':S,'from':S,'to':S,'relation':enum('requires','optional','uses','dependsOn','covers','relatedTo'),'reason':S,'designDecisionRef':S}),1),'purpose':enum('RESEARCH','INTERPRETATION','RECOMMENDATION'),'scope':SCOPE},mapvalue)
path='simulation/documents/SIM-DOC-P001_1.0.0.md';quote='期限不得超过 12 个月。';ev={'sourceId':'SIM-DOC-P001','sourceVersion':'1.0.0','path':path,'quote':quote,'quoteHash':hashlib.sha256(quote.encode()).hexdigest(),'sourceHash':hashlib.sha256((R/path).read_bytes()).hexdigest()}
add('Assertion',{'assertionId':S,'subjectRef':S,'predicate':S,'value':S,'modality':enum('FACT_CLAIM','FORECAST','OPINION','NORMATIVE_RULE'),'knowledgeState':enum('CANDIDATE','SUPPORTED','UNKNOWN','CONFLICT'),'validTime':PERIOD,'scope':SCOPE,'evidence':arr(LOC,1),'extractionRunId':S}, {'assertionId':'SIM-AS-001','subjectRef':'SIM-P001','predicate':'maxTenorMonths','value':'12','modality':'NORMATIVE_RULE','knowledgeState':'SUPPORTED','validTime':{'from':'2026-09-01','to':'2026-10-01'},'scope':scope,'evidence':[ev],'extractionRunId':'SIM-EXTRACT-AUTHORED-001'})
metric={'metricId':'SIM.METRIC.CUSTOMER_AVG_DEPOSIT','version':'1.0.0','ownerSystem':'SEMANTIC_SERVICE','ownerRole':'SIM-METRIC-OWNER','approvalRef':'SIM-METRIC-APPROVAL','baseGrain':['accountId','businessDate'],'aggregationGrain':['customerId','period'],'calendarPolicy':'CALENDAR_DAYS','timezone':'Asia/Shanghai','currencyPolicy':'CNY_ONLY','unit':'YUAN','nullPolicy':'REJECT_MISSING_DAY','rounding':'HALF_UP_2','queryId':'SIM-QRY-AVG-DEPOSIT','mappingVersion':'1.0.0','formula':'ROUND_HALF_UP(SUM(account_day.closingBalance)/COUNT(calendar_days),2)'}
add('MetricDefinition',{'metricId':S,'version':VER,'ownerSystem':enum('SEMANTIC_SERVICE'),'ownerRole':S,'approvalRef':S,'baseGrain':arr(S,1),'aggregationGrain':arr(S,1),'calendarPolicy':enum('CALENDAR_DAYS'),'timezone':enum('Asia/Shanghai'),'currencyPolicy':enum('CNY_ONLY'),'unit':enum('YUAN'),'nullPolicy':enum('REJECT_MISSING_DAY'),'rounding':enum('HALF_UP_2'),'queryId':S,'mappingVersion':VER,'formula':S},metric)
req={'metricId':metric['metricId'],'metricVersion':'1.0.0','customerId':'SIM-C001','period':{'from':'2026-09-01','to':'2026-10-01'},'snapshotId':'SIM-SNAPSHOT-20261001','currency':'CNY','purpose':'INTERPRETATION'}
add('SemanticRequest',{'metricId':S,'metricVersion':VER,'customerId':S,'period':PERIOD,'snapshotId':S,'currency':enum('CNY'),'purpose':enum('RESEARCH','INTERPRETATION','RECOMMENDATION')},req)
res={'metricId':metric['metricId'],'metricVersion':'1.0.0','value':'2983333.33','currency':'CNY','unit':'YUAN','period':req['period'],'asOf':'2026-10-01T00:00:00+08:00','snapshotId':req['snapshotId'],'mappingVersion':'1.0.0','queryId':metric['queryId'],'queryRunId':'SIM-QRUN-001','permissionDecisionRef':'SIM-PERM-001','completeness':'COMPLETE','calculationDetailRef':'simulation/oracles/expected.json','warnings':[]}
add('SemanticResult',{'metricId':S,'metricVersion':VER,'value':MONEY,'currency':enum('CNY'),'unit':enum('YUAN'),'period':PERIOD,'asOf':S,'snapshotId':S,'mappingVersion':VER,'queryId':S,'queryRunId':S,'permissionDecisionRef':S,'completeness':enum('COMPLETE','INCOMPLETE'),'calculationDetailRef':S,'warnings':arr(S)},res)
plan={'planId':'SIM-PLAN-001','taskId':'SIM-TASK-001','mapRef':{'id':'SIM-MAP-FINANCE','version':'1.0.0'},'releaseId':'SIM-REL-001','coreVersion':'1.0.0','catalogRevision':1,'routePolicyVersion':'1.0.0','assetRefs':[{'id':'SIM-ASSET-METRIC','version':'1.0.0'},{'id':'SIM-ASSET-P001','version':'1.0.0'}],'capabilityRefs':[{'id':'SIM-CAP-INTERPRET','version':'1.0.0'}],'queryRefs':[{'id':metric['queryId'],'version':'1.0.0'}],'steps':[{'stepId':'STEP-1','executorRef':metric['queryId'],'dependencies':[],'sideEffect':'READ_ONLY'},{'stepId':'STEP-2','executorRef':'SIM-CAP-INTERPRET','dependencies':['STEP-1'],'sideEffect':'READ_ONLY'}],'permissionDecisionRef':'SIM-PERM-001','purpose':'INTERPRETATION','scope':scope,'budget':{'maxSteps':8,'maxTokens':12000,'timeoutMs':120000},'planHash':'0'*64}
add('ActivationPlan',{'planId':S,'taskId':S,'mapRef':REF,'releaseId':S,'coreVersion':VER,'catalogRevision':{'type':'integer','minimum':1},'routePolicyVersion':VER,'assetRefs':arr(REF,1),'capabilityRefs':arr(REF,1),'queryRefs':arr(REF),'steps':arr(obj({'stepId':S,'executorRef':S,'dependencies':arr(S),'sideEffect':enum('READ_ONLY')}),1),'permissionDecisionRef':S,'purpose':enum('RESEARCH','INTERPRETATION','RECOMMENDATION'),'scope':SCOPE,'budget':obj({'maxSteps':{'type':'integer','minimum':1,'maximum':20},'maxTokens':{'type':'integer','minimum':1,'maximum':12000},'timeoutMs':{'type':'integer','minimum':1,'maximum':120000}}),'planHash':H},plan)
plan_core={k:v for k,v in examples['ActivationPlan'].items() if k not in ['planId','planHash']};examples['ActivationPlan']['planHash']=digest(plan_core)
add('EvidenceBundle',{'bundleId':S,'planId':S,'releaseId':S,'permissionDecisionRef':S,'facts':arr(obj({'factId':S,'sourceRef':S,'value':S,'asOf':S})),'claims':arr(obj({'claimId':S,'modality':enum('FORECAST','OPINION','FACT_CLAIM'),'sourceRef':S,'text':S})),'evidence':arr(LOC,1),'ruleResults':arr(obj({'ruleId':S,'result':enum('TRUE','FALSE','UNKNOWN'),'reason':S})),'unknowns':arr(S),'conflicts':arr(S),'scope':SCOPE}, {'bundleId':'SIM-BUNDLE-001','planId':'SIM-PLAN-001','releaseId':'SIM-REL-001','permissionDecisionRef':'SIM-PERM-001','facts':[{'factId':'SIM-FACT-AVG','sourceRef':'examples/positive/SemanticResult.json','value':'2983333.33','asOf':res['asOf']}],'claims':[{'claimId':'SIM-CLAIM-001','modality':'FORECAST','sourceRef':'simulation/documents/SIM-VISIT-001_1.0.0.md','text':'下季度可能需要 3000 万用于备货，期限和担保方式还没定。'}],'evidence':[ev],'ruleResults':[{'ruleId':'SIM-RULE-PURPOSE','result':'UNKNOWN','reason':'用途与担保条件仍待核实'}],'unknowns':['期限','担保条件'],'conflicts':[],'scope':scope})
add('ControlledAction',{'actionId':S,'taskId':S,'actionType':enum('CREATE_FOLLOWUP_TASK','RECORD_CONTACT_OUTCOME'),'customerId':S,'parametersHash':H,'confirmationRef':S,'targetVersion':{'type':'integer','minimum':1},'idempotencyKey':S,'mode':enum('SIMULATION'),'purpose':S}, {'actionId':'SIM-ACTION-001','taskId':'SIM-TASK-001','actionType':'CREATE_FOLLOWUP_TASK','customerId':'SIM-C001','parametersHash':digest({'followup':'核实用途、币种、期限和担保条件','customerId':'SIM-C001'}),'confirmationRef':'SIM-CONFIRM-001','targetVersion':1,'idempotencyKey':'SIM-ACTION-001-ATTEMPT','mode':'SIMULATION','purpose':'核实融资需求'})
add('GraphRequest',{'queryId':enum('SIM-GQ-HOLDINGS'),'queryVersion':VER,'entityId':S,'releaseId':S,'maxHops':{'type':'integer','minimum':1,'maximum':3},'maxNodes':{'type':'integer','minimum':1,'maximum':50},'scope':SCOPE}, {'queryId':'SIM-GQ-HOLDINGS','queryVersion':'1.0.0','entityId':'SIM-C001','releaseId':'SIM-GRAPH-1','maxHops':1,'maxNodes':20,'scope':scope})
add('GraphResponse',{'queryId':S,'projectionVersion':S,'paths':arr(obj({'entityIds':arr(S,2),'edgeIds':arr(S,1),'sourceRefs':arr(S,1)})),'truncated':B,'warnings':arr(S)}, {'queryId':'SIM-GQ-HOLDINGS','projectionVersion':'SIM-GRAPH-1','paths':[{'entityIds':['SIM-C001','SIM-P001'],'edgeIds':['SIM-H001'],'sourceRefs':['simulation/tables/holdings.csv#SIM-H001']}],'truncated':False,'warnings':[]})
# All examples are simulation workflow fixtures. They do not attest real approvals.
releasepayload={'releaseId':'SIM-REL-001','version':'1.0.0','coreVersion':'1.0.0','purposeFlags':['INTERPRETATION'],'artifactRefs':[{'path':'examples/positive/KnowledgeMap.json','hash':digest(examples['KnowledgeMap'])},{'path':'examples/positive/Assertion.json','hash':digest(examples['Assertion'])},{'path':'examples/positive/AssetVersion.json','hash':digest(examples['AssetVersion'])}],'requiredProjectionKinds':['MAP','RAG'],'graphRequired':False}
add('ReviewDecision',{'decisionId':S,'targetId':S,'targetVersion':VER,'targetHash':H,'reviewerPrincipal':S,'authorPrincipal':S,'reviewerRole':enum('KNOWLEDGE_OWNER','MAP_OWNER','METRIC_OWNER'),'decision':enum('APPROVED','REJECTED'),'purpose':enum('RESEARCH','INTERPRETATION','RECOMMENDATION'),'reason':S}, {'decisionId':'SIM-REVIEW-001','targetId':'SIM-REL-001','targetVersion':'1.0.0','targetHash':digest(releasepayload),'reviewerPrincipal':'SIM-REVIEWER','authorPrincipal':'SIM-AUTHOR','reviewerRole':'KNOWLEDGE_OWNER','decision':'APPROVED','purpose':'INTERPRETATION','reason':'仅模拟：确认来源、用途与内容哈希'})
add('ReleaseManifest',{'payload':obj({'releaseId':S,'version':VER,'coreVersion':VER,'purposeFlags':arr(enum('RESEARCH','INTERPRETATION','RECOMMENDATION'),1),'artifactRefs':arr(obj({'path':S,'hash':H}),1),'requiredProjectionKinds':arr(enum('MAP','RAG','GRAPH'),1),'graphRequired':B}),'payloadHash':H,'approvalRefs':arr(S,1),'projectionStates':arr(obj({'kind':enum('MAP','RAG','GRAPH'),'state':enum('READY','PENDING','FAILED')}),1),'status':enum('STAGED','PUBLISHED')}, {'payload':releasepayload,'payloadHash':digest(releasepayload),'approvalRefs':['SIM-REVIEW-001','SIM-MAP-DESIGN-001'],'projectionStates':[{'kind':'MAP','state':'READY'},{'kind':'RAG','state':'READY'}],'status':'PUBLISHED'})
mapreview=copy.deepcopy(examples['ReviewDecision']);mapreview.update(decisionId='SIM-MAP-DESIGN-001',reviewerPrincipal='SIM-MAP-REVIEWER',reviewerRole='MAP_OWNER',reason='仅模拟：认定任务、资产与能力依赖关系')
write('simulation/map_review_decision.json',mapreview)
# Scope of minimal profiles explicitly excludes detailed authentication and transport envelopes.
mutations={
'SemanticPackage': [('ownerSystem','KERT'),('version','latest')],
'AssetVersion':[('assetClass','PRODUCT'),('contentHash','not-a-hash')],
'KnowledgeMap':[('entryNodes',[]),('purpose','EXECUTE_TRANSFER')],
'Assertion':[('evidence',[]),('modality','ABSOLUTE_TRUTH')],
'ReviewDecision':[('targetHash',''),('reviewerRole','LLM_SELF_APPROVER')],
'ReleaseManifest':[('approvalRefs',[]),('payloadHash','bad')],
'MetricDefinition':[('nullPolicy','FILL_ZERO'),('currencyPolicy','ADD_ALL_CURRENCIES')],
'SemanticRequest':[('currency','USD'),('metricVersion','latest')],
'SemanticResult':[('value',2983333.33),('permissionDecisionRef','')],
'ActivationPlan':[('steps',[]),('planHash','')],
'EvidenceBundle':[('evidence',[]),('permissionDecisionRef','')],
'ControlledAction':[('mode','PRODUCTION'),('actionType','TRANSFER_FUNDS')],
'GraphRequest':[('maxHops',100),('queryId','ARBITRARY_CYPHER')],
'GraphResponse':[('projectionVersion',''),('truncated','false')]}
checks=[]
for name,schema in schemas.items():
 write(f'schemas/{name}.schema.json',schema);write(f'examples/positive/{name}.json',examples[name])
 for i,(key,val) in enumerate(mutations[name],1):
  bad=copy.deepcopy(examples[name]);bad[key]=val;p=f'examples/negative/{name}_{i}.json';write(p,bad);checks.append({'path':p,'schema':name,'expected':'SCHEMA_REJECT','reason':key+' 非法值或必需内容缺失'})
write('examples/schema_cases.json',checks)
# Registry simulation fixtures, each with a valid AssetVersion schema.
registry=[examples['AssetVersion']]
for aid,kind,owner,content in [('SIM-ASSET-METRIC','METRIC','SEMANTIC_SERVICE','examples/positive/MetricDefinition.json'),('SIM-CAP-INTERPRET','SKILL','KERT','simulation/capability_contract.json')]:
 a=copy.deepcopy(examples['AssetVersion']);a.update(assetId=aid,assetClass='PROCESS_TOOL' if kind=='SKILL' else 'KNOWLEDGE_RULE',kind=kind,ownerSystem=owner,contentRef=content,title=aid,dependencyRefs=[{'id':'SIM-ASSET-P001','version':'1.0.0'}] if kind=='SKILL' else [])
 registry.append(a)
cap={'capabilityId':'SIM-CAP-INTERPRET','version':'1.0.0','inputSchemaRef':'SemanticRequest','outputSchemaRef':'EvidenceBundle','executorRef':'KERT.ProductInterpretation','sideEffect':'READ_ONLY','preconditions':['授权范围内','已发布产品资产可用'],'status':'SIMULATED_CONTRACT_ONLY','productionProbePassed':False,'simulationOnly':True}
write('simulation/capability_contract.json',cap)
for a in registry[1:]:a['contentHash']=hashlib.sha256((R/a['contentRef']).read_bytes()).hexdigest()
write('simulation/registry_snapshot.json',registry)
write('simulation/confirmation_fixture.json',{'confirmationId':'SIM-CONFIRM-001','customerId':'SIM-C001','actionType':'CREATE_FOLLOWUP_TASK','parametersHash':examples['ControlledAction']['parametersHash'],'targetVersion':1,'reviewer':'SIM-BUSINESS-REVIEWER','simulationOnly':True,'isRealApproval':False})
index=[]
link={'C01':['SemanticPackage'],'C02':['AssetVersion','KnowledgeMap'],'C03':['Assertion','ReviewDecision','ReleaseManifest'],'C04':['MetricDefinition','SemanticRequest','SemanticResult'],'C05':['GraphRequest','GraphResponse'],'C06':['ActivationPlan','EvidenceBundle','ControlledAction'],'C07':[],'C08':[]}
for cid,names in link.items():
 doc=next((R/'contracts').glob(cid+'*.md'));index.append({'contractId':cid,'version':'1.0.0','status':'CONTRACT_CANDIDATE','path':str(doc.relative_to(R)),'sha256':hashlib.sha256(doc.read_bytes()).hexdigest(),'schemas':[f'schemas/{n}.schema.json' for n in names],'positiveExamples':[f'examples/positive/{n}.json' for n in names],'negativeExamples':[f'examples/negative/{n}_{i}.json' for n in names for i in [1,2]],'compatibility':'NEW_CANDIDATE_PROFILE_REQUIRES_EXISTING_CONTRACT_MAPPING'})
write('CONTRACT_INDEX.json',{'packageId':'GK-KE-CONTRACT-V1.0','productionReady':False,'independentQa':'NOT_PERFORMED','contracts':index})
print(json.dumps({'schemas':len(schemas),'positive':len(examples),'negative':len(checks)}))
